language: cpp

compiler:
#  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

  apt_packages:
    - swig3.0

before_script:
  - mkdir build
  - pushd build
  - export CODECOV_TOKEN="0696851b-d4f9-4eb0-bb17-15b81bc69a32"

script:
  - cmake -DUSE_SWIG=ON -DUSE_GTEST=ON -DUSE_GCOV=ON ..
  - make
  - make coverage
#  - make test
#  - ./bin/unittest
  - ../py/run.sh ../py/test.py

after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
